server:
  port: 8081
spring:
  security:
    user:
      name: admin
      password: 123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bar-mysql:37306/bar?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: jiaCHUN@#!

